advantages-01
vladibon/ice-cream pull request #10
Opened 2021-06-04 20:48 UTC by Dmitriff

2021-06-04 21:06 UTC, KonstantinZakrzhevskyi requested changes

2021-06-04 21:06 UTC, KonstantinZakrzhevskyi commented on src/partials/advantages.html
> +  <h2 class="">advantages</h2>
После  <section> оберни все содержимое в <div class="container">

2021-06-04 21:06 UTC, KonstantinZakrzhevskyi commented on src/partials/advantages.html
> +      <p>Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
Всем <p> (абзацам) можно сразу дать класс. Их в дальнейшем тоже нужно будет стилизировать.

2021-06-04 21:12 UTC, Olena-Horobets commented on src/partials/advantages.html
> +      <span class="section__title">721</span>
это точно не section__title. Такой класс можно присвоить H2

2021-06-04 21:12 UTC, Olena-Horobets commented on src/partials/advantages.html
> +      <span class="section__title">721</span>
только назови его более специфично, чтоб не скрылись случайно заголовки других секций

2021-06-04 21:22 UTC, Anna-Sergeevna commented on src/partials/advantages.html
> +  <h2 class="">advantages</h2>
добавь заголовку класс visually-hidden

2021-06-04 21:59 UTC, Dmitriff commented on src/partials/advantages.html
> +  <h2 class="">advantages</h2>
добавил

2021-06-04 21:59 UTC, Dmitriff commented on src/partials/advantages.html
> +      <span class="section__title">721</span>
сменил

2021-06-04 21:59 UTC, Dmitriff commented on src/partials/advantages.html
> +      <p>Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
задал

2021-06-04 22:00 UTC, Dmitriff commented on src/partials/advantages.html
> +  <h2 class="">advantages</h2>
обернул

2021-06-04 22:17 UTC, Anna-Sergeevna requested changes

2021-06-04 22:17 UTC, Anna-Sergeevna commented on src/partials/advantages.html
> +<h2 class="visually-hidden">advantages</h2>
Верни h2 на ворую строчку.
Сделай структуру:
`section class="section`
`h2 class="visually-hidden">advantages</h2`
`div class=container`
`ul`

2021-06-04 22:29 UTC, Dmitriff commented on src/partials/advantages.html
> +<h2 class="visually-hidden">advantages</h2>
ok

2021-06-04 22:29 UTC, Dmitriff commented on src/partials/advantages.html
> +  <h2 class="">advantages</h2>
не ок

2021-06-04 22:49 UTC, vladibon requested changes

2021-06-04 22:49 UTC, vladibon commented on src/partials/advantages.html
> +<h2 class="visually-hidden">advantages</h2>
h2 в секции должен быть

2021-06-04 22:49 UTC, vladibon commented on src/partials/advantages.html
> +<section class="section">
```
<section class="section">
   <div class="container">

   </div>
</section>
```

В секции еще нужен контейнер

2021-06-04 22:49 UTC, vladibon commented on src/partials/advantages.html
> +      <p class="text-font">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
Вместо text-font лучше напиши: grid__text

2021-06-04 22:49 UTC, vladibon commented on src/partials/advantages.html
> +        <p class="text-font">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
Напиши grid__text вместо text-font

2021-06-04 22:53 UTC, vladibon approved these changes

2021-06-05 08:54 UTC, vladibon requested changes

2021-06-05 08:54 UTC, vladibon commented on src/partials/advantages.html
> +        <p class="text-font">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
Напиши, пожалуйста `grid__descr` вместо `text-font`

2021-06-05 09:05 UTC, Dmitriff commented on src/partials/advantages.html
> +        <p class="text-font">Aliquam ac dui vel dui vulputate consectetur. Mauris massa.</p>
сделал

2021-06-05 09:10 UTC, vladibon approved these changes

2021-06-05 09:10 UTC, merged