Feature/pege header
vladibon/ice-cream pull request #11
Opened 2021-06-04 21:20 UTC by Eduard-Konovka

Набросал хедер с мобильным меню. На классы не обращайте внимания - будут переделываться

2021-06-04 21:34 UTC, Olena-Horobets approved these changes

2021-06-04 21:34 UTC, Olena-Horobets commented on src/partials/page-header.html
> +    <nav class="nav">
можно два nav если один скрыт? я просто не в курсе, я в одном делала)

2021-06-04 21:34 UTC, Olena-Horobets commented on src/partials/page-header.html
> +        <svg>
пойду искать иконку))))

2021-06-04 21:43 UTC, Eduard-Konovka commented on src/partials/page-header.html
> +    <nav class="nav">
Хз. Я делал два. Юля говорила, что отдельное меню мобильного хедера легче поддерживать - это обеспечивает простоту css

2021-06-04 21:51 UTC, Eduard-Konovka commented on src/partials/page-header.html
> +    <nav class="nav">
По логике всё равно видна только одна навигация, вторая - display: none; 
Не знаю только точно как это работает в ассистивных технологиях. "display: none;" прячет, по идее, всё и от всего, в т.ч. и от ассистивных технологий

2021-06-05 08:45 UTC, vladibon requested changes

2021-06-05 08:45 UTC, vladibon commented on src/partials/page-header.html
> +<header class="pege-header u-container u-flexbox">
Нужен еще контейнер, который оборачивает и центрирует header.
`<div class="container page-header__container">`

Классы u-container u-flexbox думаю не пригодятся. Можно убрать.

2021-06-05 08:45 UTC, vladibon commented on src/partials/page-header.html
> +        <ul class="nav__list u-list">
модификатор лучше написать по бэм. 
не `u-list`, а `nav__list--center `, например.
Вряди ли он пригодится. можно убрать.

2021-06-05 08:45 UTC, vladibon commented on src/partials/page-header.html
> +    <div class="menu-container" id="menu-container" data-menu>
Лучше просто `menu` или `mobile-menu`
Слово `container` ассоциируется с центрирующим контейнером. Он у нас один.

2021-06-05 08:45 UTC, vladibon commented on src/partials/page-header.html
> +        <nav class="nav">
Класс `nav` уже есть.
Здесь тогда будет `mobile-nav`

2021-06-06 14:44 UTC, closed without merging