feature/footer-scss
vladibon/ice-cream pull request #23
Opened 2021-06-05 18:04 UTC by KonstantinZakrzhevskyi

Добавляет стилизацию подвала для мобильного и создает паршал _social-links.scss

2021-06-05 19:21 UTC, Olena-Horobets approved these changes
looks great)

2021-06-06 05:42 UTC, vladibon requested changes

2021-06-06 05:42 UTC, vladibon commented on src/partials/page-footer.html
>      <p class="copyright">&copy; 2019 - IceCream. All Rights Reserved.</p>
`copyright`  нужно вынести из `div container` и на него дать` border-top,` чтоб линия тянулась на весь экран.

2021-06-06 05:42 UTC, vladibon commented on src/sass/layout/_page-footer.scss
> +  margin-right: auto;
маржины будут не нужны, если copyright  вынести из div container

2021-06-06 05:42 UTC, vladibon commented on src/sass/layout/_page-footer.scss
> +  padding-bottom: 43px;
`padding-bottom: 43px;` должен быть на `.footer__socials`

2021-06-06 05:42 UTC, vladibon commented on src/sass/layout/_page-footer.scss
> +    margin-bottom: 43px;
Это ене `margin-bottom: 43px;`, а `padding-bottom: 43px;` для `footer__content`
Еще у `footer`  должен быть `padding-top: 70px;`.
Остальное расстояние Ира добавит.
Если хочешь можешь согласовать сам с ней, как вы делите паддинги между футером и ее секцией.

2021-06-06 08:06 UTC, KonstantinZakrzhevskyi commented on src/sass/layout/_page-footer.scss
> +  padding-bottom: 43px;
Исправил

2021-06-06 08:16 UTC, KonstantinZakrzhevskyi commented on src/sass/layout/_page-footer.scss
> +  margin-right: auto;
Маржины нужны для центрирования текста

2021-06-06 08:17 UTC, KonstantinZakrzhevskyi commented on src/sass/layout/_page-footer.scss
> +    margin-bottom: 43px;
Исправил

2021-06-06 12:19 UTC, KonstantinZakrzhevskyi commented on src/partials/page-footer.html
>      <p class="copyright">&copy; 2019 - IceCream. All Rights Reserved.</p>
Исправил

2021-06-06 17:03 UTC, merged