advantages/03
vladibon/ice-cream pull request #24
Opened 2021-06-05 19:23 UTC by Dmitriff

2021-06-05 20:19 UTC, Olena-Horobets reviewed
вроде ок

2021-06-05 20:20 UTC, Olena-Horobets approved these changes

2021-06-06 06:10 UTC, vladibon requested changes
Well done! Несколько правок всего.

2021-06-06 06:10 UTC, vladibon commented on src/sass/layout/_advantages.scss
> +.grid__title {
Поставь, пожалуйста, везде `p` вместо `span`  и сверь `margin-bottom: 38px;` с макетом.

2021-06-06 06:10 UTC, vladibon commented on src/sass/layout/_advantages.scss
> +  &__item {
Нужно `max-width: 230px` для мобильной версии. Для планшета, и десктопа может быть другой `max-width` чтобы текст переносился как на макете.

2021-06-06 06:10 UTC, vladibon commented on src/sass/layout/_advantages.scss
> +.grid__descr {
Для мобильной версии торчит нижний маржин у последнего `grid__descr`. Нужно `margin-bottom: 0;` через дополнительный класс `grid__descr--last`. Повесить этот класс только на последий `p`.

2021-06-06 16:50 UTC, KonstantinZakrzhevskyi approved these changes

2021-06-06 16:50 UTC, KonstantinZakrzhevskyi commented on src/sass/layout/_advantages.scss
>    @media screen and(min-width:768px) {
Можно заменить @media на  @include respond-above($tablet)

2021-06-06 17:52 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
> +.grid__title {
сменил , проверил

2021-06-06 17:53 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
> +.grid__descr {
убрал маржин

2021-06-06 17:53 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
>    @media screen and(min-width:768px) {
заменил и таб и деск

2021-06-06 18:11 UTC, Olena-Horobets commented on src/sass/layout/_advantages.scss
> +.grid__title {
Я может не вижу изменений , но у р висит нижний маржин, пробивающий родителя. Задав ему margin-bottom: 0; на мобиле можешь удалить на последующих медиаправилах. И на мобилке отступы 38px между li

2021-06-06 18:19 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
> +  &__item {
поправил

2021-06-06 20:27 UTC, KonstantinZakrzhevskyi requested changes

2021-06-06 20:27 UTC, KonstantinZakrzhevskyi commented on src/partials/advantages.html
> +</sectip>
Опечатка sectip =section

2021-06-06 20:31 UTC, KonstantinZakrzhevskyi approved these changes

2021-06-06 20:31 UTC, KonstantinZakrzhevskyi commented on src/sass/layout/_advantages.scss
> +  font-weight: 700;
font-weight: 700; можно один раз записать, дальше на всех точках перелома он такой и истанется

2021-06-06 20:48 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
> +  font-weight: 700;
знаю решил наверняка

2021-06-06 20:54 UTC, Dmitriff commented on src/partials/advantages.html
> +</sectip>
очепятку убрал

2021-06-06 20:55 UTC, Dmitriff commented on src/sass/layout/_advantages.scss
> +  font-weight: 700;
убрал

2021-06-06 21:00 UTC, merged