feature/products
vladibon/ice-cream pull request #34
Opened 2021-06-06 18:02 UTC by Anna-Sergeevna

Добавляет псевдоэлемент "..."

Есть псевдоэлементы карточек, но без позиционирования.

Добавляет placeholder для мое секции.

2021-06-06 19:27 UTC, Olena-Horobets requested changes

2021-06-06 19:27 UTC, Olena-Horobets commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
У абзаца на мобиле font-size: 14px ;

2021-06-06 19:27 UTC, Olena-Horobets commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
попробуй before спозиционировать относительно product карточки

2021-06-06 19:27 UTC, Olena-Horobets commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
попробуй, если хочешь этот миксин для ретины. очень удобно) он уже прописан, только путь ставишь   

 @include retina-display(2) {
      background-image: url();
    }

2021-06-06 19:47 UTC, Anna-Sergeevna commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
Я когда стили писала, в common основной текст был 14рх. Не заметила изменений.

2021-06-06 19:47 UTC, Anna-Sergeevna commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
Завтра посмотрю.

2021-06-06 19:48 UTC, Anna-Sergeevna commented on src/partials/products.html
>                      <p class="product__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
Я так и делаю)

2021-06-06 19:49 UTC, KonstantinZakrzhevskyi approved these changes

2021-06-07 08:26 UTC, Olena-Horobets approved these changes

2021-06-07 08:26 UTC, merged